
class LED
{
private:
    int index = 0; 
public:
    void init_LED();
    void LED_on_off(int LEDarry[]);

//******************************************LEDS***************************/
//**LED Arry Number   0       1      2       3     4      5      6      7      8       9      10     11     12     13     14    15    16 17//
//**Col A LEDS**//
    int LEDA1[18] = {OUTPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, OUTPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, 9, 1};
    int LEDA2[18] = {INPUT, OUTPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, OUTPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, 9, 2};
    int LEDA3[18] = {INPUT, INPUT, OUTPUT, INPUT, INPUT, INPUT, INPUT, INPUT, OUTPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, 9, 3};
    int LEDA4[18] = {INPUT, INPUT, INPUT, OUTPUT, INPUT, INPUT, INPUT, INPUT, OUTPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, 9, 4};
    int LEDA5[18] = {INPUT, INPUT, INPUT, INPUT, OUTPUT, INPUT, INPUT, INPUT, OUTPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, 9, 5};
    int LEDA6[18] = {INPUT, INPUT, INPUT, INPUT, INPUT, OUTPUT, INPUT, INPUT, OUTPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, 9, 6};
    int LEDA7[18] = {INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, OUTPUT, INPUT, OUTPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, 9, 7};
    int LEDA8[18] = {INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, OUTPUT, OUTPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, 9, 8};
//**Col B LEDS**//

// ********* LED Clear *****//
    int LEDclear[18] = {INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, INPUT, 0 , 0};
}; // end Class LED